### ISSUE TITLE
Add cache module

### ISSUE THREAD

**Issue by kiyonlin** [go-dawn/module#4]
Supported drivers
- [x] memory
- [x] redis
- [x] gorm

**Comment by kiyonlin** [comment]
Configuration section for cache module.
```toml
# config.toml
[Cache]
# default cache in use
Default = "memory"

[Cache.Storage]
[Cache.Storage.memory]
Driver = "memory"
GCInterval = "10s"

[Cache.Storage.redis]
Driver = "redis"
# Connection name in redis section
Connection = "cache"
Prefix = "dawn_cache_"

[Cache.Storage.sql]
Driver = "gorm"
# Connection name in sql section
Connection = "cache"
Table = "dawn_cache"
Prefix = "dawn_cache_"
GCInterval = "10s"
```
